### ISSUE TITLE
Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Watchdog Dev

### ISSUE THREAD

**Issue by crasu** [alex107ivanov/hassio-addons#1]
Versions:
core-2022.3.1
supervisor-2022.03.5

With a current home assistant I get the above warning in the log.

Probably you only have to change the startup" entry in config.json to "system" or "services".

**Comment by alex107ivanov** [comment]
Hey! Thank you for your issue report. I fixed it in 0.0.10 version. Please check if this warning goes away.

**Comment by crasu** [comment]
Works! Thank you!
