### ISSUE TITLE
How to install and how to know if watchdog worked?

### ISSUE THREAD

**Issue by swa72** [alex107ivanov/hassio-addons#2]
Hi,

I managed to install the add-on via Settings | Add-ons | Add-on Store | three dots on top right | Repositories and adding the URL of this repo. 

Having started the add-on, the log shows

```
2022-10-03 19:20:46 INFO     Opening watchdog device
2022-10-03 19:20:46 INFO     Watchdog identity: Broadcom BCM2835 Watchdog timer
2022-10-03 19:20:46 INFO     Watchdog firmware version: 0
2022-10-03 19:20:46 INFO     Watchdog options: 33152
2022-10-03 19:20:46 INFO     Watchdog timeout: 15
2022-10-03 19:20:46 INFO     Starting main cycle with sleep time 5 sec...
```

So far so good. Is there any way to get noticed once the watchdog has restarted the RPI?

**Comment by alex107ivanov** [comment]
Hi,
As for me I added two notifications in HA on shutdown and on startup - if you only get startup message watchdog can be a reason:

- id: "Hass Startup Notification"
  alias: 'Hass Startup Notification'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: notify.telegram_notify
    data:
      title: "Warning"
      message: "Hass restarted"

- id: "Hass Shutdown Notification"
  alias: 'Hass Shutdown Notification'
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    service: notify.telegram_notify
    data:
      title: "Warning"
      message: "Hass shutdown"

**Comment by swa72** [comment]
Thanks for the hint, discovered that myself in one of your other postings ;-) I am eager for HA to break down again to see if the watchdog works ..

**Comment by alex107ivanov** [comment]
Hi! Glad to hear it)
After i created this tool mine HA stops halting) Some kind of magic) To check that it works you can kill -9 process inside watchdog container,  -9 will prevent it from stopping hardware watchdog timer, if watchdog container will not start back nobody will send pings to hardware watchdog. After timeout your raspberry should reboot. It's not fully correct experiment, but it will check hardware watchdog is working.
